#include "GameplayTags/T7_GameplayTags.h"

namespace T7GameplayTags
{
	UE_DEFINE_GAMEPLAY_TAG(BP_CLASS_WEAPON_1, "BP.Class.Weapon1");
	
	UE_DEFINE_GAMEPLAY_TAG(DA_INPUT_ACTION, "DA.Input.Action");
	UE_DEFINE_GAMEPLAY_TAG(INPUT_ACTION_MOVE, "Input.Action.Move");
	UE_DEFINE_GAMEPLAY_TAG(INPUT_ACTION_LOOK, "Input.Action.Look");
	UE_DEFINE_GAMEPLAY_TAG(INPUT_ACTION_AIM, "Input.Action.Aim");
	UE_DEFINE_GAMEPLAY_TAG(INPUT_ACTION_FIRE, "Input.Action.Fire");
	UE_DEFINE_GAMEPLAY_TAG(INPUT_ACTION_JUMP, "Input.Action.Jump");
	UE_DEFINE_GAMEPLAY_TAG(INPUT_ACTION_PICKUP, "Input.Action.Pickup");
	UE_DEFINE_GAMEPLAY_TAG(INPUT_ACTION_SPRINT, "Input.Action.Sprint");
	UE_DEFINE_GAMEPLAY_TAG(INPUT_ACTION_SWITCHCAMERA, "Input.Action.SwitchCamera");
	UE_DEFINE_GAMEPLAY_TAG(INPUT_ACTION_RELOAD, "Input.Action.Reload");
}
