#pragma once

#include "NativeGameplayTags.h"

namespace T7_InputTag
{
	// Secondary Data Asset
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(DA_INPUT_ACTION);
	
	// Input
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(INPUT_ACTION_MOVE);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(INPUT_ACTION_LOOK);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(INPUT_ACTION_AIM);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(INPUT_ACTION_FIRE);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(INPUT_ACTION_JUMP);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(INPUT_ACTION_PICKUP);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(INPUT_ACTION_SPRINT);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(INPUT_ACTION_SWITCHCAMERA);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(INPUT_ACTION_RELOAD);
}
namespace T7_BPClassTag
{
	// Secondary Data Asset
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(DA_BPClass);

	// Enemy
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(BP_CLASS_ENEMY_NORMAL);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(BP_CLASS_ENEMY_ELITE);

	// ItemBox
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(BP_CLASS_ITEMBOX_WEAPON);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(BP_CLASS_ITEMBOX_MEDIKIT);
	
}