#pragma once

#include "NativeGameplayTags.h"

namespace T7GameplayTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(BP_CLASS_WEAPON_1);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(DA_INPUT_ACTION);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(INPUT_ACTION_MOVE);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(INPUT_ACTION_LOOK);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(INPUT_ACTION_AIM);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(INPUT_ACTION_FIRE);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(INPUT_ACTION_JUMP);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(INPUT_ACTION_PICKUP);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(INPUT_ACTION_SPRINT);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(INPUT_ACTION_SWITCHCAMERA);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(INPUT_ACTION_RELOAD);
	
}
